import 'package:islami_app/model/sura_dm.dart';

List<SuraDm> suraList = [
  SuraDm(
    arabicName: "الفاتحه",
    englishName: "Al-Fatiha",
    ayaCount: 7,
    index: 1,
  ),
  SuraDm(
    arabicName: "البقرة",
    englishName: "Al-Baqarah",
    ayaCount: 286,
    index: 2,
  ),
  SuraDm(
    arabicName: "آل عمران",
    englishName: "Aal-E-Imran",
    ayaCount: 200,
    index: 3,
  ),
  SuraDm(
    arabicName: "النساء",
    englishName: "An-Nisa'",
    ayaCount: 176,
    index: 4,
  ),
  SuraDm(
    arabicName: "المائدة",
    englishName: "Al-Ma'idah",
    ayaCount: 120,
    index: 5,
  ),
  SuraDm(
    arabicName: "الأنعام",
    englishName: "Al-An'am",
    ayaCount: 165,
    index: 6,
  ),
  SuraDm(
    arabicName: "الأعراف",
    englishName: "Al-A'raf",
    ayaCount: 206,
    index: 7,
  ),
  SuraDm(
    arabicName: "الأنفال",
    englishName: "Al-Anfal",
    ayaCount: 75,
    index: 8,
  ),
  SuraDm(
    arabicName: "التوبة",
    englishName: "At-Tawbah",
    ayaCount: 129,
    index: 9,
  ),
  SuraDm(arabicName: "يونس", englishName: "Yunus", ayaCount: 109, index: 10),
  SuraDm(arabicName: "هود", englishName: "Hud", ayaCount: 123, index: 11),
  SuraDm(arabicName: "يوسف", englishName: "Yusuf", ayaCount: 111, index: 12),
  SuraDm(arabicName: "الرعد", englishName: "Ar-Ra'd", ayaCount: 43, index: 13),
  SuraDm(
    arabicName: "إبراهيم",
    englishName: "Ibrahim",
    ayaCount: 52,
    index: 14,
  ),
  SuraDm(arabicName: "الحجر", englishName: "Al-Hijr", ayaCount: 99, index: 15),
  SuraDm(arabicName: "النحل", englishName: "An-Nahl", ayaCount: 128, index: 16),
  SuraDm(
    arabicName: "الإسراء",
    englishName: "Al-Isra",
    ayaCount: 111,
    index: 17,
  ),
  SuraDm(arabicName: "الكهف", englishName: "Al-Kahf", ayaCount: 110, index: 18),
  SuraDm(arabicName: "مريم", englishName: "Maryam", ayaCount: 98, index: 19),
  SuraDm(arabicName: "طه", englishName: "Ta-Ha", ayaCount: 135, index: 20),
  SuraDm(
    arabicName: "الأنبياء",
    englishName: "Al-Anbiya",
    ayaCount: 112,
    index: 21,
  ),
  SuraDm(arabicName: "الحج", englishName: "Al-Hajj", ayaCount: 78, index: 22),
  SuraDm(
    arabicName: "المؤمنون",
    englishName: "Al-Mu'minun",
    ayaCount: 118,
    index: 23,
  ),
  SuraDm(arabicName: "النّور", englishName: "An-Nur", ayaCount: 64, index: 24),
  SuraDm(
    arabicName: "الفرقان",
    englishName: "Al-Furqan",
    ayaCount: 77,
    index: 25,
  ),
  SuraDm(
    arabicName: "الشعراء",
    englishName: "Ash-Shu'ara",
    ayaCount: 227,
    index: 26,
  ),
  SuraDm(arabicName: "النّمل", englishName: "An-Naml", ayaCount: 93, index: 27),
  SuraDm(arabicName: "القصص", englishName: "Al-Qasas", ayaCount: 88, index: 28),
  SuraDm(
    arabicName: "العنكبوت",
    englishName: "Al-Ankabut",
    ayaCount: 69,
    index: 29,
  ),
  SuraDm(arabicName: "الرّوم", englishName: "Ar-Rum", ayaCount: 60, index: 30),
  SuraDm(arabicName: "لقمان", englishName: "Luqman", ayaCount: 34, index: 31),
  SuraDm(
    arabicName: "السجدة",
    englishName: "As-Sajda",
    ayaCount: 30,
    index: 32,
  ),
  SuraDm(
    arabicName: "الأحزاب",
    englishName: "Al-Ahzab",
    ayaCount: 73,
    index: 33,
  ),
  SuraDm(arabicName: "سبأ", englishName: "Saba", ayaCount: 54, index: 34),
  SuraDm(arabicName: "فاطر", englishName: "Fatir", ayaCount: 45, index: 35),
  SuraDm(arabicName: "يس", englishName: "Ya-Sin", ayaCount: 83, index: 36),
  SuraDm(
    arabicName: "الصافات",
    englishName: "As-Saffat",
    ayaCount: 182,
    index: 37,
  ),
  SuraDm(arabicName: "ص", englishName: "Sad", ayaCount: 88, index: 38),
  SuraDm(arabicName: "الزمر", englishName: "Az-Zumar", ayaCount: 75, index: 39),
  SuraDm(arabicName: "غافر", englishName: "Ghafir", ayaCount: 85, index: 40),
  SuraDm(arabicName: "فصّلت", englishName: "Fussilat", ayaCount: 54, index: 41),
  SuraDm(
    arabicName: "الشورى",
    englishName: "Ash-Shura",
    ayaCount: 53,
    index: 42,
  ),
  SuraDm(
    arabicName: "الزخرف",
    englishName: "Az-Zukhruf",
    ayaCount: 89,
    index: 43,
  ),
  SuraDm(
    arabicName: "الدّخان",
    englishName: "Ad-Dukhan",
    ayaCount: 59,
    index: 44,
  ),
  SuraDm(
    arabicName: "الجاثية",
    englishName: "Al-Jathiya",
    ayaCount: 37,
    index: 45,
  ),
  SuraDm(
    arabicName: "الأحقاف",
    englishName: "Al-Ahqaf",
    ayaCount: 35,
    index: 46,
  ),
  SuraDm(arabicName: "محمد", englishName: "Muhammad", ayaCount: 38, index: 47),
  SuraDm(arabicName: "الفتح", englishName: "Al-Fath", ayaCount: 29, index: 48),
  SuraDm(
    arabicName: "الحجرات",
    englishName: "Al-Hujurat",
    ayaCount: 18,
    index: 49,
  ),
  SuraDm(arabicName: "ق", englishName: "Qaf", ayaCount: 45, index: 50),
  SuraDm(
    arabicName: "الذاريات",
    englishName: "Adh-Dhariyat",
    ayaCount: 60,
    index: 51,
  ),
  SuraDm(arabicName: "الطور", englishName: "At-Tur", ayaCount: 49, index: 52),
  SuraDm(arabicName: "النجم", englishName: "An-Najm", ayaCount: 62, index: 53),
  SuraDm(arabicName: "القمر", englishName: "Al-Qamar", ayaCount: 55, index: 54),
  SuraDm(
    arabicName: "الرحمن",
    englishName: "Ar-Rahman",
    ayaCount: 78,
    index: 55,
  ),
  SuraDm(
    arabicName: "الواقعة",
    englishName: "Al-Waqi'a",
    ayaCount: 96,
    index: 56,
  ),
  SuraDm(
    arabicName: "الحديد",
    englishName: "Al-Hadid",
    ayaCount: 29,
    index: 57,
  ),
  SuraDm(
    arabicName: "المجادلة",
    englishName: "Al-Mujadila",
    ayaCount: 22,
    index: 58,
  ),
  SuraDm(arabicName: "الحشر", englishName: "Al-Hashr", ayaCount: 24, index: 59),
  SuraDm(
    arabicName: "الممتحنة",
    englishName: "Al-Mumtahina",
    ayaCount: 13,
    index: 60,
  ),
  SuraDm(arabicName: "الصف", englishName: "As-Saff", ayaCount: 14, index: 61),
  SuraDm(
    arabicName: "الجمعة",
    englishName: "Al-Jumu'a",
    ayaCount: 11,
    index: 62,
  ),
  SuraDm(
    arabicName: "المنافقون",
    englishName: "Al-Munafiqun",
    ayaCount: 11,
    index: 63,
  ),
  SuraDm(
    arabicName: "التغابن",
    englishName: "At-Taghabun",
    ayaCount: 18,
    index: 64,
  ),
  SuraDm(
    arabicName: "الطلاق",
    englishName: "At-Talaq",
    ayaCount: 12,
    index: 65,
  ),
  SuraDm(
    arabicName: "التحريم",
    englishName: "At-Tahrim",
    ayaCount: 12,
    index: 66,
  ),
  SuraDm(arabicName: "الملك", englishName: "Al-Mulk", ayaCount: 30, index: 67),
  SuraDm(arabicName: "القلم", englishName: "Al-Qalam", ayaCount: 52, index: 68),
  SuraDm(
    arabicName: "الحاقة",
    englishName: "Al-Haqqah",
    ayaCount: 52,
    index: 69,
  ),
  SuraDm(
    arabicName: "المعارج",
    englishName: "Al-Ma'arij",
    ayaCount: 44,
    index: 70,
  ),
  SuraDm(arabicName: "نوح", englishName: "Nuh", ayaCount: 28, index: 71),
  SuraDm(arabicName: "الجن", englishName: "Al-Jinn", ayaCount: 28, index: 72),
  SuraDm(
    arabicName: "المزّمّل",
    englishName: "Al-Muzzammil",
    ayaCount: 20,
    index: 73,
  ),
  SuraDm(
    arabicName: "المدّثر",
    englishName: "Al-Muddathir",
    ayaCount: 56,
    index: 74,
  ),
  SuraDm(
    arabicName: "القيامة",
    englishName: "Al-Qiyamah",
    ayaCount: 40,
    index: 75,
  ),
  SuraDm(
    arabicName: "الإنسان",
    englishName: "Al-Insan",
    ayaCount: 31,
    index: 76,
  ),
  SuraDm(
    arabicName: "المرسلات",
    englishName: "Al-Mursalat",
    ayaCount: 50,
    index: 77,
  ),
  SuraDm(arabicName: "النبأ", englishName: "An-Naba'", ayaCount: 40, index: 78),
  SuraDm(
    arabicName: "النازعات",
    englishName: "An-Nazi'at",
    ayaCount: 46,
    index: 79,
  ),
  SuraDm(arabicName: "عبس", englishName: "Abasa", ayaCount: 42, index: 80),
  SuraDm(
    arabicName: "التكوير",
    englishName: "At-Takwir",
    ayaCount: 29,
    index: 81,
  ),
  SuraDm(
    arabicName: "الإنفطار",
    englishName: "Al-Infitar",
    ayaCount: 19,
    index: 82,
  ),
  SuraDm(
    arabicName: "المطفّفين",
    englishName: "Al-Mutaffifin",
    ayaCount: 36,
    index: 83,
  ),
  SuraDm(
    arabicName: "الإنشقاق",
    englishName: "Al-Inshiqaq",
    ayaCount: 25,
    index: 84,
  ),
  SuraDm(
    arabicName: "البروج",
    englishName: "Al-Buruj",
    ayaCount: 22,
    index: 85,
  ),
  SuraDm(
    arabicName: "الطارق",
    englishName: "At-Tariq",
    ayaCount: 17,
    index: 86,
  ),
  SuraDm(arabicName: "الأعلى", englishName: "Al-A'la", ayaCount: 19, index: 87),
  SuraDm(
    arabicName: "الغاشية",
    englishName: "Al-Ghashiyah",
    ayaCount: 26,
    index: 88,
  ),
  SuraDm(arabicName: "الفجر", englishName: "Al-Fajr", ayaCount: 30, index: 89),
  SuraDm(arabicName: "البلد", englishName: "Al-Balad", ayaCount: 20, index: 90),
  SuraDm(
    arabicName: "الشمس",
    englishName: "Ash-Shams",
    ayaCount: 15,
    index: 91,
  ),
  SuraDm(arabicName: "الليل", englishName: "Al-Lail", ayaCount: 21, index: 92),
  SuraDm(arabicName: "الضحى", englishName: "Ad-Duha", ayaCount: 11, index: 93),
  SuraDm(arabicName: "الشرح", englishName: "Ash-Sharh", ayaCount: 8, index: 94),
  SuraDm(arabicName: "التين", englishName: "At-Tin", ayaCount: 8, index: 95),
  SuraDm(arabicName: "العلق", englishName: "Al-Alaq", ayaCount: 19, index: 96),
  SuraDm(arabicName: "القدر", englishName: "Al-Qadr", ayaCount: 5, index: 97),
  SuraDm(
    arabicName: "البينة",
    englishName: "Al-Bayyina",
    ayaCount: 8,
    index: 98,
  ),
  SuraDm(
    arabicName: "الزلزلة",
    englishName: "Az-Zalzalah",
    ayaCount: 8,
    index: 99,
  ),
  SuraDm(
    arabicName: "العاديات",
    englishName: "Al-Adiyat",
    ayaCount: 11,
    index: 100,
  ),
  SuraDm(
    arabicName: "القارعة",
    englishName: "Al-Qari'a",
    ayaCount: 11,
    index: 101,
  ),
  SuraDm(
    arabicName: "التكاثر",
    englishName: "At-Takathur",
    ayaCount: 8,
    index: 102,
  ),
  SuraDm(arabicName: "العصر", englishName: "Al-Asr", ayaCount: 3, index: 103),
  SuraDm(
    arabicName: "الهمزة",
    englishName: "Al-Humazah",
    ayaCount: 9,
    index: 104,
  ),
  SuraDm(arabicName: "الفيل", englishName: "Al-Fil", ayaCount: 5, index: 105),
  SuraDm(arabicName: "قريش", englishName: "Quraysh", ayaCount: 4, index: 106),
  SuraDm(
    arabicName: "الماعون",
    englishName: "Al-Ma'un",
    ayaCount: 7,
    index: 107,
  ),
  SuraDm(
    arabicName: "الكوثر",
    englishName: "Al-Kawthar",
    ayaCount: 3,
    index: 108,
  ),
  SuraDm(
    arabicName: "الكافرون",
    englishName: "Al-Kafirun",
    ayaCount: 6,
    index: 109,
  ),
  SuraDm(arabicName: "النصر", englishName: "An-Nasr", ayaCount: 3, index: 110),
  SuraDm(arabicName: "المسد", englishName: "Al-Masad", ayaCount: 5, index: 111),
  SuraDm(
    arabicName: "الإخلاص",
    englishName: "Al-Ikhlas",
    ayaCount: 4,
    index: 112,
  ),
  SuraDm(arabicName: "الفلق", englishName: "Al-Falaq", ayaCount: 5, index: 113),
  SuraDm(arabicName: "الناس", englishName: "An-Nas", ayaCount: 6, index: 114),
];
